// ⚠️ THIS FILE IS ON THE MIGRATED LIST (i18n/hardcoded-strings.test.ts). Every operator-visible
// string comes from the catalog. What does NOT, and this screen is dense with it: every repeater
// callsign, output frequency, offset, CTCSS tone and DTCS code, the band chips, the mode badges
// the directory supplies (DMR / D-STAR / Fusion), the distance and octant `units.ts` formats, the
// city and state of a machine, the channel names as the radio will display them, and the
// per-radio name caps in `features/radioprog.ts` — those name RIG MODELS (FT-60, Baofeng, Yaesu,
// Anytone), which are tokens exactly as a callsign is.
//
// Four more things stay in the code as named constants, each for its own reason:
//   • the DIRECTORY NAMES (`RepeaterBook`, `hearham`) — proper nouns;
//   • the ATTRIBUTION lines the two directories require, which are also written verbatim into
//     the exported CSV, so they cannot be locale-dependent;
//   • the example grid and frequency the origin field and the by-hand prompt offer;
//   • `My channels`, the persisted project's name inside radioprog.json — a stored value, not a
//     string on screen.
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { confirmDialog } from '../confirm'
import type {
  GeoCandidate,
  ProgChannel,
  RadioProgProject,
  RepeaterSearchResult,
  RepeaterSearchRow,
} from '../types'
import {
  exportChannels,
  geocodeCity,
  radioprogListProjects,
  radioprogSaveProject,
  repeaterSearch,
  repeaterTune,
  saveTextToDownloads,
} from '../api'
import {
  addMemoryDeduped,
  findEquivalent,
  memoriesStore,
  saveFavoriteFromDial,
  updateMemory,
  useMemories,
} from '../features/memories'
import {
  autoRadiusMi,
  BAND_CHIPS,
  bandOfMhz,
  deriveNames,
  favoriteName,
  isProgrammable,
  miToKm,
  modeBadge,
  NAME_CAPS,
  octant,
  RADIUS_CHIPS_MI,
  repeaterMemory,
  rigRepeaterParams,
  sanitizeName,
} from '../features/radioprog'
import { gridToLatLon, isValidGrid } from '../grid'
import { fmtDistanceKm, useUnits } from '../units'
import { Dialog } from './ui/Dialog'
import { pushToast } from '../toast'
import { t } from '../i18n'
import { T } from '../i18n/T'
import { parseChirpCsv, type Memory } from '../features/memories'

/** The single auto-saved working project in radioprog.json (named projects can
 * layer on later — the file format already holds many). */
const WORKING_PROJECT_ID = 'working'

/** The two directories' own names, and the attribution each requires. The attribution is not
 * only shown here — `exportChannels` writes it into the CSV — so it is one invariant string in
 * both places, never a translated one in the interface and a different one in the file. */
const SOURCE_REPEATERBOOK = 'RepeaterBook'
const SOURCE_HEARHAM = 'hearham'
const ATTRIB_REPEATERBOOK = 'Data courtesy of RepeaterBook.com'
const ATTRIB_HEARHAM = 'Repeater data from hearham.com'
/** The geocoder's required credit, for the same reason. */
const ATTRIB_OSM = 'Geocoding © OpenStreetMap contributors'

/** Example values drawn from a technical namespace — a locator and a dial frequency. */
const EXAMPLE_GRID = 'FN31'
const EXAMPLE_FREQ_MHZ = '146.940'

/** The mode every programmable channel here is, and the filter chip that names it. */
const MODE_FM = 'FM'

/** localStorage for the last 5 successful query origins (chips). */
const RECENTS_KEY = 'nexus.program.recents.v1'
/** localStorage flag: the operator dismissed the CHIRP how-to dialog. */
const CHIRP_HOWTO_SEEN = 'nexus.program.chirpHowtoSeen.v1'

interface Recent {
  kind: 'grid' | 'city'
  label: string
  lat: number
  lon: number
}

function loadRecents(): Recent[] {
  try {
    const raw = JSON.parse(localStorage.getItem(RECENTS_KEY) ?? '[]')
    if (!Array.isArray(raw)) return []
    return raw
      .filter(
        (r): r is Recent =>
          r &&
          (r.kind === 'grid' || r.kind === 'city') &&
          typeof r.label === 'string' &&
          Number.isFinite(r.lat) &&
          Number.isFinite(r.lon),
      )
      .slice(0, 5)
  } catch {
    return []
  }
}

function pushRecent(r: Recent) {
  const list = [r, ...loadRecents().filter((x) => x.label !== r.label)].slice(0, 5)
  localStorage.setItem(RECENTS_KEY, JSON.stringify(list))
}

/** One builder row: the channel + whether the operator hand-edited its name
 * (edited names are never regenerated by the cap select). */
interface WorkRow {
  channel: ProgChannel
  nameEdited: boolean
}

interface Props {
  /** Station grid from Settings — the zero-input default origin. */
  myGrid: string
  /** CAT link alive — gates the per-row TUNE buttons. */
  catOk?: boolean
}

/**
 * Program — the radio-programming workbench: location → repeater directory →
 * pick → a curated channel list → CHIRP CSV / generic CSV (and, with CAT, tune
 * the rig to a machine right now). The CHANNEL LIST is the artifact; the
 * repeater results are a source feed that populates only on an explicit Fetch
 * (no auto-fetch, no polling, no map — this is a programming tool, not a
 * repeater directory).
 */
export function RadioProgView({ myGrid, catOk = false }: Props) {
  // ── query state ──
  const [originKind, setOriginKind] = useState<'station' | 'grid' | 'city'>('station')
  const [gridInput, setGridInput] = useState('')
  const [cityInput, setCityInput] = useState('')
  const [cityPick, setCityPick] = useState<GeoCandidate | null>(null)
  const [cityCands, setCityCands] = useState<GeoCandidate[]>([])
  const [geoBusy, setGeoBusy] = useState(false)
  const units = useUnits()
  const [radiusMi, setRadiusMi] = useState<number | 'auto'>('auto')
  const [bands, setBands] = useState<string[]>(['2m', '70cm'])
  const [showDigital, setShowDigital] = useState(false)
  const [onAirOnly, setOnAirOnly] = useState(true)
  const [search, setSearch] = useState('')
  const [recents, setRecents] = useState<Recent[]>(loadRecents)

  // ── results ──
  const [result, setResult] = useState<RepeaterSearchResult | null>(null)
  const [fetching, setFetching] = useState(false)
  const [fetchErr, setFetchErr] = useState('')

  // ── builder ──
  const [rows, setRows] = useState<WorkRow[]>([])
  const [nameCap, setNameCap] = useState(7)
  const [startAt, setStartAt] = useState(1)
  const [chirpDialog, setChirpDialog] = useState(false)
  const loaded = useRef(false)

  // Load the persisted working list once; save (debounced) on every change after.
  useEffect(() => {
    radioprogListProjects()
      .then((projects) => {
        const w = projects.find((p) => p.id === WORKING_PROJECT_ID)
        if (w) setRows(w.channels.map((channel) => ({ channel, nameEdited: true })))
        loaded.current = true
      })
      .catch(() => {
        loaded.current = true
      })
  }, [])
  const saveTimer = useRef<number | null>(null)
  useEffect(() => {
    if (!loaded.current) return
    if (saveTimer.current) window.clearTimeout(saveTimer.current)
    saveTimer.current = window.setTimeout(() => {
      const project: RadioProgProject = {
        id: WORKING_PROJECT_ID,
        name: 'My channels',
        createdUtc: 0,
        updatedUtc: 0,
        origin: { kind: originKind, grid: myGrid, label: originLabel(), lat: 0, lon: 0 },
        radiusKm: 0,
        channels: rows.map((r) => r.channel),
      }
      void radioprogSaveProject(project).catch(() => {})
    }, 800)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rows])

  const originLabel = useCallback((): string => {
    if (originKind === 'station') return myGrid.toUpperCase() || '—'
    if (originKind === 'grid') return gridInput.toUpperCase()
    return cityPick ? cityPick.displayName.split(',').slice(0, 2).join(',') : cityInput
  }, [originKind, myGrid, gridInput, cityPick, cityInput])

  /** Resolve the active origin to lat/lon (null = not resolvable yet). */
  const origin = useMemo((): { lat: number; lon: number } | null => {
    if (originKind === 'city') return cityPick ? { lat: cityPick.lat, lon: cityPick.lon } : null
    const g = (originKind === 'station' ? myGrid : gridInput).trim()
    if (!isValidGrid(g)) return null
    return gridToLatLon(g)
  }, [originKind, myGrid, gridInput, cityPick])

  const effRadiusMi = radiusMi === 'auto' ? autoRadiusMi(bands) : radiusMi

  const doFetch = useCallback(() => {
    if (!origin || fetching) return
    setFetching(true)
    setFetchErr('')
    repeaterSearch(origin.lat, origin.lon, miToKm(effRadiusMi))
      .then((res) => {
        setResult(res)
        const label = originLabel()
        if (label && label !== '—') {
          pushRecent({
            kind: originKind === 'city' ? 'city' : 'grid',
            label,
            lat: origin.lat,
            lon: origin.lon,
          })
          setRecents(loadRecents())
        }
      })
      .catch((e) => setFetchErr(String(e)))
      .finally(() => setFetching(false))
  }, [origin, fetching, effRadiusMi, originKind, originLabel])

  const searchCity = useCallback(() => {
    const q = cityInput.trim()
    if (!q || geoBusy) return
    setGeoBusy(true)
    setCityCands([])
    geocodeCity(q)
      .then((cands) => {
        setCityCands(cands)
        if (cands.length === 0) pushToast(t('program.city.noMatch'), 'info', 3000)
        if (cands.length === 1) setCityPick(cands[0])
      })
      .catch((e) => pushToast(String(e), 'error'))
      .finally(() => setGeoBusy(false))
  }, [cityInput, geoBusy])

  const useRecent = (r: Recent) => {
    // Recents carry resolved coordinates — re-fetch immediately from them.
    setOriginKind(r.kind === 'city' ? 'city' : 'grid')
    if (r.kind === 'grid') setGridInput(r.label)
    else {
      setCityInput(r.label)
      setCityPick({ displayName: r.label, lat: r.lat, lon: r.lon })
    }
  }

  // ── filtered picker rows ──
  const shown = useMemo(() => {
    if (!result) return []
    const q = search.trim().toUpperCase()
    return result.rows.filter((row) => {
      const r = row.record
      const band = bandOfMhz(r.outputMhz)
      if (bands.length > 0 && !bands.includes(band)) return false
      if (!showDigital && !r.fm) return false
      if (onAirOnly && !r.operational) return false
      if (q && !r.callsign.toUpperCase().includes(q) && !r.city.toUpperCase().includes(q))
        return false
      return true
    })
  }, [result, bands, showDigital, onAirOnly, search])

  const inList = useMemo(() => new Set(rows.map((r) => r.channel.id)), [rows])

  // Which shown machines are already starred — live from the shared bank, so the
  // stars stay right when the operator unstars one in the Memories section.
  const bank = useMemories()
  const starredIds = useMemo(() => {
    const out = new Set<string>()
    for (const row of shown) {
      const input = repeaterMemory(row.channel, '')
      const hit = findEquivalent(bank, {
        rxMhz: input.rxMhz,
        mode: input.mode,
        ctcssEncHz: input.ctcssEncHz,
      })
      if (hit?.favorite) out.add(row.channel.id)
    }
    return out
  }, [shown, bank])

  // ── builder ops ──
  /** A Memory (a CHIRP CSV row) as a Program channel — the reverse of `saveToBank`. Manual
   * and imported rows carry a `manual:` id so re-imports dedup. */
  const memoryToChannel = (m: Memory): ProgChannel => ({
    id: `manual:${m.rxMhz.toFixed(4)}:${m.name}`,
    name: m.name,
    rxMhz: m.rxMhz,
    duplex:
      m.offsetDir === 'split' ? 'split' : m.offsetDir === 'plus' ? 'plus' : m.offsetDir === 'minus' ? 'minus' : 'simplex',
    offsetMhz: m.offsetDir === 'split' ? (m.txMhz ?? m.rxMhz) - m.rxMhz : (m.offsetMhz ?? 0),
    toneMode: m.toneMode === 'tone' || m.toneMode === 'tsql' || m.toneMode === 'dtcs' ? m.toneMode : 'none',
    rtoneHz: m.ctcssEncHz ?? 0,
    ctoneHz: m.ctcssDecHz ?? m.ctcssEncHz ?? 0,
    dtcsCode: m.dtcsCode ?? 0,
    mode: m.mode.trim().toLowerCase() === 'nfm' ? 'nfm' : m.mode.trim().toLowerCase() === 'am' ? 'am' : 'fm',
    comment: m.notes ?? '',
    source: null,
  })

  /** Manual channel entry (operator ask, 2026-08-16): the directory is a FEED, and a repeater
   * it has wrong or missing must be enterable by hand — HearHam's coverage is thin in places
   * and the shared RepeaterBook path is still pending approval. */
  const addManual = () => {
    const freq = window.prompt(t('program.manual.freq', { example: EXAMPLE_FREQ_MHZ }))
    if (!freq) return
    const rxMhz = Number(freq)
    if (!Number.isFinite(rxMhz) || rxMhz <= 0) return
    const name = window.prompt(t('program.manual.name')) ?? ''
    const off = window.prompt(t('program.manual.offset')) ?? ''
    const tone = window.prompt(t('program.manual.tone')) ?? ''
    const toneHz = Number(tone)
    const ch: ProgChannel = {
      id: `manual:${rxMhz.toFixed(4)}:${name || 'manual'}`,
      name: name || `${rxMhz.toFixed(3)} FM`,
      rxMhz,
      duplex: off.trim() === '+' ? 'plus' : off.trim() === '-' ? 'minus' : 'simplex',
      offsetMhz: 0,
      toneMode: Number.isFinite(toneHz) && toneHz > 0 ? 'tone' : 'none',
      rtoneHz: Number.isFinite(toneHz) && toneHz > 0 ? toneHz : 0,
      ctoneHz: 0,
      dtcsCode: 0,
      mode: 'fm',
      comment: '',
      source: null,
    }
    setRows((rs) =>
      rs.some((r) => r.channel.id === ch.id) ? rs : [...rs, { channel: ch, nameEdited: name !== '' }],
    )
  }

  const importInputRef = useRef<HTMLInputElement>(null)
  const importCsv = async (file: File) => {
    const text = await file.text()
    const mems = parseChirpCsv(text)
    if (mems.length === 0) {
      pushToast(t('program.import.notChirp'), 'error')
      return
    }
    setRows((rs) => {
      const have = new Set(rs.map((r) => r.channel.id))
      const add = mems.map(memoryToChannel).filter((c) => !have.has(c.id))
      return [...rs, ...add.map((channel) => ({ channel, nameEdited: true }))]
    })
    pushToast(t('program.import.done', { count: mems.length }), 'success')
  }

  const addRow = (row: RepeaterSearchRow) => {
    if (inList.has(row.channel.id)) {
      setRows((rs) => rs.filter((r) => r.channel.id !== row.channel.id))
      return
    }
    setRows((rs) => [...rs, { channel: { ...row.channel }, nameEdited: false }])
  }
  const addAllShown = async () => {
    const candidates = shown.filter(
      (row) => isProgrammable(row.record) && !inList.has(row.channel.id),
    )
    if (candidates.length === 0) return
    if (
      candidates.length > 50 &&
      !(await confirmDialog({
        title: t('program.addAll.confirm.title', { count: candidates.length }),
        confirmLabel: t('program.addAll.confirm.ok'),
      }))
    )
      return
    setRows((rs) => [
      ...rs,
      ...candidates.slice(0, 200).map((row) => ({ channel: { ...row.channel }, nameEdited: false })),
    ])
  }
  const move = (i: number, d: -1 | 1) => {
    setRows((rs) => {
      const j = i + d
      if (j < 0 || j >= rs.length) return rs
      const next = rs.slice()
      ;[next[i], next[j]] = [next[j], next[i]]
      return next
    })
  }
  const remove = (i: number) => setRows((rs) => rs.filter((_, k) => k !== i))
  const rename = (i: number, name: string) =>
    setRows((rs) =>
      rs.map((r, k) => (k === i ? { ...r, channel: { ...r.channel, name }, nameEdited: true } : r)),
    )

  // Auto-derived names for rows the operator hasn't touched (cap-aware).
  const displayRows = useMemo(() => {
    const auto = deriveNames(
      rows.map((r) => ({
        callsign: r.channel.source?.callsign ?? r.channel.name,
        city: r.channel.comment,
        outputMhz: r.channel.rxMhz,
      })),
      nameCap,
    )
    return rows.map((r, i) => ({
      ...r,
      displayName: r.nameEdited ? r.channel.name : auto[i],
    }))
  }, [rows, nameCap])

  const dupNames = useMemo(() => {
    const seen = new Map<string, number>()
    for (const r of displayRows) {
      const n = sanitizeName(r.displayName, nameCap)
      seen.set(n, (seen.get(n) ?? 0) + 1)
    }
    return new Set([...seen.entries()].filter(([, c]) => c > 1).map(([n]) => n))
  }, [displayRows, nameCap])

  const attribution = result?.source === 'repeaterbook' ? ATTRIB_REPEATERBOOK : ATTRIB_HEARHAM

  const exportList = (format: 'chirp' | 'csv') => {
    const channels = displayRows.map((r) => ({ ...r.channel, name: r.displayName }))
    const analog = channels.filter((c) => c.mode === 'fm' || c.mode === 'nfm' || c.mode === 'am')
    if (format === 'chirp' && analog.length === 0) {
      pushToast(t('program.export.noFm'), 'info')
      return
    }
    void exportChannels(channels, format, nameCap, attribution)
      .then((text) => {
        const stamp = new Date().toISOString().slice(0, 10)
        const name = format === 'chirp' ? `nexus-chirp-${stamp}.csv` : `nexus-channels-${stamp}.csv`
        return saveTextToDownloads(name, text).then((path) => {
          pushToast(
            format === 'chirp'
              ? t('program.export.saved.chirp', { path })
              : t('program.export.saved', { path }),
            'success',
            6000,
          )
        })
      })
      .catch((e) => pushToast(String(e), 'error'))
  }

  const onExportChirp = () => {
    if (localStorage.getItem(CHIRP_HOWTO_SEEN) === '1') exportList('chirp')
    else setChirpDialog(true)
  }

  /** Tune the CAT rig to a repeater NOW — one atomic backend step that routes on
   * FM (so 2 m repeater work reaches the FM radio even when the operator came
   * from a digital section) and lands the shift/offset/tone with the QSY. */
  const tuneTo = (c: ProgChannel) => {
    const { shift, offsetHz, toneHz } = rigRepeaterParams(c)
    void repeaterTune(c.rxMhz, shift, offsetHz, toneHz)
      .then(() => {
        // The shift is a sign and a number of MHz — a token, assembled here; only the word
        // "simplex" and the tone clause are prose.
        const shiftLabel =
          shift === 'simplex'
            ? t('program.tune.simplex')
            : `${shift === 'plus' ? '+' : '−'}${(offsetHz / 1e6).toFixed(2)} MHz`
        pushToast(
          t('program.tune.done', {
            freq: c.rxMhz.toFixed(4),
            mode: MODE_FM,
            shift: shiftLabel,
            tone: toneHz ? t('program.tune.tone', { hz: toneHz.toFixed(1) }) : '',
          }),
          'success',
          4000,
        )
      })
      .catch((e) => pushToast(String(e), 'error'))
  }

  /** ★ one machine straight into the favorites list — the whole point of the
   * feature: fetch, star, and it's on the cockpit MEM strip and in Memories
   * without a trip through the channel-list builder. Starring an equivalent
   * channel the bank already holds stars THAT row rather than duplicating it
   * (memoryKey identity), and the star toggles back off. */
  const toggleStar = (row: RepeaterSearchRow) => {
    // The name is bound here rather than read back off `input`, whose type makes every
    // Memory field optional — it is `input.name` by construction, and a string.
    const favName = favoriteName(row.channel)
    const input = repeaterMemory(row.channel, favName, {
      lat: row.record.lat,
      lon: row.record.lon,
    })
    let msg = ''
    memoriesStore.update((bank) => {
      const existing = findEquivalent(bank, {
        rxMhz: input.rxMhz,
        mode: input.mode,
        ctcssEncHz: input.ctcssEncHz,
      })
      if (existing?.favorite) {
        msg = t('program.star.unstarred', { name: existing.name })
        return updateMemory(bank, existing.id, { favorite: false })
      }
      const res = saveFavoriteFromDial(bank, input)
      msg =
        res.result === 'starred'
          ? t('program.star.starred', { name: existing?.name ?? favName })
          : t('program.star.saved', { name: favName })
      return res.bank
    })
    pushToast(msg, 'success', 4000)
  }

  /** Save the whole list into the shared Memories store (with the FM repeater
   * fields, so recall keys the machine — not just the output). Deduped on
   * freq+mode+tone so re-saving the same list never piles duplicates; the
   * SHARED store means the Memories section + cockpit MEM strips update live
   * (the old direct-to-storage write went stale until reload). */
  const saveToBank = () => {
    let n = 0
    let dup = 0
    memoriesStore.update((bank) => {
      let next = bank
      for (const r of displayRows) {
        const c = r.channel
        if (!(c.mode === 'fm' || c.mode === 'nfm' || c.mode === 'am')) continue
        // No site coordinates here: the builder list persists channels only
        // (radioprog.json), so a reloaded row has no record to read lat/lon from.
        // ★-ing from the results list is the path that carries them.
        const res = addMemoryDeduped(
          next,
          repeaterMemory(c, sanitizeName(r.displayName, nameCap) || c.name),
        )
        next = res.bank
        if (res.added) n += 1
        else dup += 1
      }
      return next
    })
    // The already-there clause is interpolated INTO the sentence rather than glued onto it: it
    // carries the second count, which one message cannot pluralise alongside the first, and a
    // language that words the pair differently can still place it.
    pushToast(
      n
        ? t('program.saveBank.done', {
            count: n,
            dupes: dup ? t('program.saveBank.dupes', { count: dup }) : '',
          })
        : dup
          ? t('program.saveBank.allDupes')
          : t('program.saveBank.noFm'),
      n ? 'success' : 'info',
      5000,
    )
  }

  // The unit letter rides inside the message with its number, so a translation can never
  // separate the two.
  const fmtAge = (unix: number): string => {
    const mins = Math.max(0, Math.round((Date.now() / 1000 - unix) / 60))
    if (mins < 60) return t('program.age.mins', { mins })
    if (mins < 60 * 48) return t('program.age.hours', { hours: Math.round(mins / 60) })
    return t('program.age.days', { days: Math.round(mins / 1440) })
  }

  const offsetLabel = (c: ProgChannel): string => {
    if (c.duplex === 'simplex') return '—'
    if (c.duplex === 'split') return `→${c.offsetMhz.toFixed(3)}`
    return `${c.duplex === 'plus' ? '+' : '-'}${c.offsetMhz.toFixed(1)}`
  }
  const toneLabel = (c: ProgChannel): string => {
    if (c.toneMode === 'none') return '—'
    if (c.toneMode === 'dtcs') return `D${String(c.dtcsCode).padStart(3, '0')}`
    return c.rtoneHz.toFixed(1)
  }

  return (
    <section className="radioprog panel">
      <div className="panel-header">
        <h2>{t('program.title')}</h2>
        <span className="awards-sub">{t('program.sub')}</span>
      </div>

      <div className="rp-body">
        {/* ── SOURCE pane: the query tool ── */}
        <div className="rp-source">
          <div className="rp-origin" role="group" aria-label={t('program.origin.aria')}>
            <span className="rp-lbl">{t('program.origin.label')}</span>
            <button
              type="button"
              className={`filter-chip${originKind === 'station' ? ' active' : ''}`}
              onClick={() => setOriginKind('station')}
              title={t('program.origin.station.title')}
            >
              {t('program.origin.station.label', {
                grid: myGrid ? `· ${myGrid.toUpperCase()}` : '',
              })}
            </button>
            <button
              type="button"
              className={`filter-chip${originKind === 'grid' ? ' active' : ''}`}
              onClick={() => setOriginKind('grid')}
            >
              {t('program.origin.grid.label')}
            </button>
            <button
              type="button"
              className={`filter-chip${originKind === 'city' ? ' active' : ''}`}
              onClick={() => setOriginKind('city')}
            >
              {t('program.origin.city.label')}
            </button>
            {originKind === 'grid' && (
              <input
                type="text"
                className={`settings-input mono rp-grid${gridInput && !isValidGrid(gridInput.trim()) ? ' invalid' : ''}`}
                value={gridInput}
                maxLength={6}
                placeholder={EXAMPLE_GRID}
                aria-label={t('program.origin.grid.aria')}
                onChange={(e) => setGridInput(e.target.value.toUpperCase())}
              />
            )}
            {originKind === 'city' && (
              <span className="rp-city">
                <input
                  type="text"
                  className="settings-input rp-city-input"
                  value={cityInput}
                  placeholder={t('program.origin.city.placeholder')}
                  aria-label={t('program.origin.city.aria')}
                  onChange={(e) => {
                    setCityInput(e.target.value)
                    setCityPick(null)
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') searchCity()
                  }}
                />
                <button
                  type="button"
                  className="filter-chip"
                  onClick={searchCity}
                  disabled={geoBusy || !cityInput.trim()}
                >
                  {geoBusy ? t('program.city.searching') : t('program.city.search')}
                </button>
              </span>
            )}
          </div>
          {originKind === 'city' && cityCands.length > 1 && !cityPick && (
            <div className="rp-city-cands" role="listbox" aria-label={t('program.city.matches.aria')}>
              {cityCands.map((c) => (
                <button
                  key={c.displayName}
                  type="button"
                  className="filter-chip"
                  onClick={() => setCityPick(c)}
                >
                  {c.displayName}
                </button>
              ))}
            </div>
          )}
          {recents.length > 0 && (
            <div className="rp-recents" role="group" aria-label={t('program.recent.aria')}>
              <span className="rp-lbl">{t('program.recent.label')}</span>
              {recents.map((r) => (
                <button
                  key={r.label}
                  type="button"
                  className="filter-chip rp-recent"
                  onClick={() => useRecent(r)}
                  title={t('program.recent.chip.title')}
                >
                  {r.label}
                </button>
              ))}
            </div>
          )}

          <div className="rp-radius" role="group" aria-label={t('program.radius.aria')}>
            <span className="rp-lbl">{t('program.radius.label')}</span>
            {RADIUS_CHIPS_MI.map((mi) => (
              <button
                key={mi}
                type="button"
                className={`filter-chip${radiusMi === mi ? ' active' : ''}`}
                onClick={() => setRadiusMi(mi)}
              >
                {fmtDistanceKm(mi * 1.609344, units)}
              </button>
            ))}
            <button
              type="button"
              className={`filter-chip${radiusMi === 'auto' ? ' active' : ''}`}
              onClick={() => setRadiusMi('auto')}
              title={t('program.radius.auto.title')}
            >
              {t('program.radius.auto.label')}
            </button>
            {radiusMi === 'auto' && (
              <span className="rp-hint">
                {t('program.radius.auto.hint', {
                  radius: fmtDistanceKm(effRadiusMi * 1.609344, units),
                  bands: bands.length ? bands.join('+') : t('program.radius.auto.allBands'),
                })}
              </span>
            )}
          </div>

          <div className="rp-fetch-row">
            <button
              type="button"
              className="filter-chip pota-refresh-btn rp-fetch"
              onClick={doFetch}
              disabled={!origin || fetching}
              title={
                origin
                  ? t('program.fetch.title', {
                      radius: fmtDistanceKm(effRadiusMi * 1.609344, units),
                    })
                  : t('program.fetch.title.noOrigin')
              }
            >
              {fetching ? t('program.fetch.busy') : t('program.fetch.label')}
            </button>
            {result && (
              <span className="rp-stamp" title={t('program.stamp.title')}>
                {result.source === 'repeaterbook' ? SOURCE_REPEATERBOOK : SOURCE_HEARHAM} ·{' '}
                {fmtAge(result.fetchedUtc)}
                {result.stale ? t('program.stamp.stale') : ''}
              </span>
            )}
          </div>
          {fetchErr && (
            <div className="rp-error" role="alert">
              {fetchErr}{' '}
              <button type="button" className="filter-chip" onClick={doFetch}>
                {t('program.fetch.retry')}
              </button>
            </div>
          )}
          {result?.coverageGap && (
            <div className="rp-note" role="status">
              <T
                k="program.coverageGap"
                tags={{ b: <strong /> }}
                vals={{ source: SOURCE_HEARHAM, band: result.coverageGap }}
              />
            </div>
          )}

          <div className="rp-filters" role="group" aria-label={t('program.filters.aria')}>
            <button
              type="button"
              className={`filter-chip${bands.length === 0 ? ' active' : ''}`}
              onClick={() => setBands([])}
            >
              {t('program.filters.allBands')}
            </button>
            {BAND_CHIPS.map((b) => (
              <button
                key={b}
                type="button"
                className={`filter-chip${bands.includes(b) ? ' active' : ''}`}
                onClick={() =>
                  setBands((bs) => (bs.includes(b) ? bs.filter((x) => x !== b) : [...bs, b]))
                }
              >
                {b}
              </button>
            ))}
            <span className="rp-filter-gap" />
            <button
              type="button"
              className={`filter-chip${!showDigital ? ' active' : ''}`}
              onClick={() => setShowDigital(false)}
              title={t('program.filters.fm.title')}
            >
              {MODE_FM}
            </button>
            <button
              type="button"
              className={`filter-chip${showDigital ? ' active' : ''}`}
              onClick={() => setShowDigital(true)}
              title={t('program.filters.digital.title')}
            >
              {t('program.filters.digital.label')}
            </button>
            <button
              type="button"
              className={`filter-chip${onAirOnly ? ' active' : ''}`}
              onClick={() => setOnAirOnly((v) => !v)}
              title={t('program.filters.onAir.title')}
            >
              {t('program.filters.onAir.label')}
            </button>
            <input
              type="search"
              className="settings-input rp-search"
              value={search}
              placeholder={t('program.filters.search.placeholder')}
              aria-label={t('program.filters.search.aria')}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          {result && (
            <div className="rp-count">
              {t('program.count', { shown: shown.length, total: result.rows.length })}
              {shown.some((r) => isProgrammable(r.record) && !inList.has(r.channel.id)) && (
                <button type="button" className="filter-chip" onClick={addAllShown}>
                  {t('program.addAll.label')}
                </button>
              )}
            </div>
          )}

          <div className="rp-results" role="table" aria-label={t('program.results.aria')}>
            {!result && !fetching && (
              <p className="aw-empty">
                <T k="program.results.prompt" tags={{ b: <strong /> }} />
              </p>
            )}
            {result && shown.length === 0 && (
              <p className="aw-empty">
                {/* Two whole sentences, not one with an "FM " fragment spliced in: where the
                    mode word sits in the sentence is the translator's to decide. */}
                {showDigital
                  ? t('program.results.none', {
                      radius: fmtDistanceKm(effRadiusMi * 1.609344, units),
                    })
                  : t('program.results.none.fm', {
                      radius: fmtDistanceKm(effRadiusMi * 1.609344, units),
                    })}
                {radiusMi !== 200 && (
                  <button
                    type="button"
                    className="filter-chip"
                    onClick={() => setRadiusMi(radiusMi === 'auto' ? 100 : 200)}
                  >
                    {t('program.results.tryWider', {
                      radius: fmtDistanceKm((radiusMi === 'auto' ? 100 : 200) * 1.609344, units),
                    })}
                  </button>
                )}
                {!showDigital && (
                  <button type="button" className="filter-chip" onClick={() => setShowDigital(true)}>
                    {t('program.results.showDigital')}
                  </button>
                )}
              </p>
            )}
            {shown.map((row) => {
              const r = row.record
              const c = row.channel
              const added = inList.has(c.id)
              const programmable = isProgrammable(r)
              const badge = modeBadge(r)
              return (
                <div
                  key={c.id}
                  role="row"
                  className={`rp-row${!r.operational ? ' offair' : ''}${!programmable ? ' digital' : ''}`}
                >
                  <span className="rp-call mono" role="cell">
                    {r.callsign || '—'}
                  </span>
                  <span className="rp-freq mono" role="cell">
                    {r.outputMhz.toFixed(4).replace(/0+$/, '').replace(/\.$/, '.0')}
                  </span>
                  <span className="rp-off mono" role="cell">
                    {offsetLabel(c)}
                  </span>
                  <span className="rp-tone mono" role="cell">
                    {toneLabel(c)}
                  </span>
                  <span className="rp-dist mono" role="cell" title={`${r.city}${r.state ? `, ${r.state}` : ''}`}>
                    {fmtDistanceKm(r.distanceKm, units)} {octant(r.bearingDeg)}
                  </span>
                  <span className="rp-badges" role="cell">
                    {badge && <span className="pota-badge rp-mode-badge">{badge}</span>}
                    {!r.operational && (
                      <span className="pota-badge rp-offair-badge">{t('program.row.offAir')}</span>
                    )}
                  </span>
                  <span className="rp-actions" role="cell">
                    {programmable && (
                      <button
                        type="button"
                        className={`rp-star${starredIds.has(c.id) ? ' on' : ''}`}
                        onClick={() => toggleStar(row)}
                        aria-pressed={starredIds.has(c.id)}
                        title={
                          starredIds.has(c.id)
                            ? t('program.row.unstar.title')
                            : t('program.row.star.title')
                        }
                      >
                        {starredIds.has(c.id) ? '★' : '☆'}
                      </button>
                    )}
                    {catOk && programmable && (
                      <button
                        type="button"
                        className="pota-hunt-btn rp-tune"
                        onClick={() => tuneTo(c)}
                        title={t('program.row.tune.title')}
                      >
                        {t('program.row.tune.label')}
                      </button>
                    )}
                    <button
                      type="button"
                      className={`pota-hunt-btn rp-add${added ? ' added' : ''}`}
                      disabled={!programmable && !added}
                      onClick={() => addRow(row)}
                      title={
                        programmable
                          ? added
                            ? t('program.row.remove.title')
                            : t('program.row.add.title')
                          : t('program.row.add.digital.title')
                      }
                    >
                      {added ? t('program.row.added.label') : t('program.row.add.label')}
                    </button>
                  </span>
                </div>
              )
            })}
          </div>

          <div className="settings-hint rp-attribution">
            {result?.source === 'hearham' || !result ? (
              <a href="https://hearham.com" target="_blank" rel="noreferrer">
                {ATTRIB_HEARHAM}
              </a>
            ) : (
              <a href="https://www.repeaterbook.com" target="_blank" rel="noreferrer">
                {ATTRIB_REPEATERBOOK}
              </a>
            )}
            {originKind === 'city' && <span> · {ATTRIB_OSM}</span>}
          </div>
        </div>

        {/* ── CHANNEL LIST pane: the artifact ── */}
        <aside className="rp-builder">
          <div className="rp-builder-head">
            <span className="rp-builder-title">
              {t('program.builder.title')} <span className="np-count">{rows.length}</span>
            </span>
            <label className="rp-cap">
              {t('program.builder.nameCap.label')}
              {/* The option labels name RIG MODELS (`features/radioprog.ts`) — tokens. */}
              <select
                className="settings-input"
                value={nameCap}
                onChange={(e) => setNameCap(Number(e.target.value))}
                title={t('program.builder.nameCap.title')}
              >
                {NAME_CAPS.map((c) => (
                  <option key={c.cap} value={c.cap}>
                    {c.label}
                  </option>
                ))}
              </select>
            </label>
            <label className="rp-startat" title={t('program.builder.startAt.title')}>
              {t('program.builder.startAt.label')}
              <input
                type="number"
                className="settings-input"
                min={1}
                max={999}
                value={startAt}
                onChange={(e) => setStartAt(Math.max(1, Math.round(Number(e.target.value) || 1)))}
              />
            </label>
          </div>

          <div className="rp-chan-rows">
            {displayRows.length === 0 && <p className="aw-empty">{t('program.builder.empty')}</p>}
            {displayRows.map((r, i) => {
              const clean = sanitizeName(r.displayName, nameCap)
              const dup = dupNames.has(clean)
              const over = r.displayName.trim().length > nameCap
              return (
                <div key={r.channel.id} className={`rp-chan-row${dup ? ' dup' : ''}`}>
                  <span className="rp-chan-num mono">{startAt + i}</span>
                  <input
                    type="text"
                    className={`settings-input mono rp-chan-name${dup || over ? ' invalid' : ''}`}
                    value={r.displayName}
                    maxLength={24}
                    aria-label={t('program.chan.name.aria', { n: startAt + i })}
                    onChange={(e) => rename(i, e.target.value)}
                    title={
                      dup
                        ? t('program.chan.dup.title')
                        : over
                          ? t('program.chan.over.title', { cap: nameCap, name: clean })
                          : undefined
                    }
                  />
                  <span className="rp-chan-freq mono">{r.channel.rxMhz.toFixed(4)}</span>
                  <span className="rp-chan-off mono">{offsetLabel(r.channel)}</span>
                  <span className="rp-chan-tone mono">{toneLabel(r.channel)}</span>
                  <span className="rp-chan-btns">
                    <button
                      type="button"
                      onClick={() => move(i, -1)}
                      disabled={i === 0}
                      aria-label={t('program.chan.moveUp.aria')}
                    >
                      ▲
                    </button>
                    <button
                      type="button"
                      onClick={() => move(i, 1)}
                      disabled={i === displayRows.length - 1}
                      aria-label={t('program.chan.moveDown.aria')}
                    >
                      ▼
                    </button>
                    <button type="button" onClick={() => remove(i)} aria-label={t('program.chan.remove.aria')}>
                      ✕
                    </button>
                  </span>
                </div>
              )
            })}
          </div>

          <div className="rp-deliver">
            <button
              type="button"
              className="settings-refresh"
              onClick={addManual}
              title={t('program.deliver.byHand.title')}
            >
              {t('program.deliver.byHand.label')}
            </button>
            <button
              type="button"
              className="settings-refresh"
              onClick={() => importInputRef.current?.click()}
              title={t('program.deliver.import.title')}
            >
              {t('program.deliver.import.label')}
            </button>
            <input
              ref={importInputRef}
              type="file"
              accept=".csv"
              hidden
              onChange={(e) => {
                const f = e.target.files?.[0]
                if (f) void importCsv(f)
                e.target.value = ''
              }}
            />
            <button
              type="button"
              className="settings-save rp-export-chirp"
              disabled={rows.length === 0}
              onClick={onExportChirp}
              title={t('program.deliver.exportChirp.title')}
            >
              {t('program.deliver.exportChirp.label')}
            </button>
            <button
              type="button"
              className="settings-refresh"
              disabled={rows.length === 0}
              onClick={() => exportList('csv')}
              title={t('program.deliver.exportCsv.title')}
            >
              {t('program.deliver.exportCsv.label')}
            </button>
            <button
              type="button"
              className="settings-refresh"
              disabled={rows.length === 0}
              onClick={saveToBank}
              title={t('program.deliver.saveBank.title')}
            >
              {t('program.deliver.saveBank.label')}
            </button>
            <button
              type="button"
              className="settings-refresh rp-clear"
              disabled={rows.length === 0}
              onClick={() => {
                void (async () => {
                  if (
                    await confirmDialog({
                      title: t('program.clear.confirm.title'),
                      confirmLabel: t('program.clear.confirm.ok'),
                      danger: true,
                    })
                  )
                    setRows([])
                })()
              }}
            >
              {t('program.deliver.clear.label')}
            </button>
          </div>
        </aside>
      </div>

      <Dialog
        open={chirpDialog}
        onOpenChange={setChirpDialog}
        title={t('program.chirp.title')}
        description={t('program.chirp.description')}
      >
        {/* CHIRP's own menu path stays inside the sentence, marked but not translated apart. */}
        <ol className="rp-chirp-steps">
          <li>{t('program.chirp.step.save')}</li>
          <li>
            <T k="program.chirp.step.import" tags={{ b: <strong /> }} />
          </li>
          <li>
            <T k="program.chirp.step.upload" tags={{ b: <strong /> }} />
          </li>
        </ol>
        <p className="settings-hint">
          <a href="https://chirpmyradio.com" target="_blank" rel="noreferrer">
            {t('program.chirp.link')}
          </a>
        </p>
        <div className="rp-chirp-actions">
          <label className="settings-hint rp-chirp-skip">
            <input
              type="checkbox"
              onChange={(e) => {
                if (e.target.checked) localStorage.setItem(CHIRP_HOWTO_SEEN, '1')
                else localStorage.removeItem(CHIRP_HOWTO_SEEN)
              }}
            />
            {t('program.chirp.dontShow')}
          </label>
          <button
            type="button"
            className="settings-save"
            onClick={() => {
              setChirpDialog(false)
              exportList('chirp')
            }}
          >
            {t('program.chirp.save')}
          </button>
        </div>
      </Dialog>
    </section>
  )
}
