import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { confirmDialog } from '../confirm'
import type {
  GeoCandidate,
  ProgChannel,
  RadioProgProject,
  RepeaterSearchResult,
  RepeaterSearchRow,
} from '../types'
import {
  exportChannels,
  geocodeCity,
  radioprogListProjects,
  radioprogSaveProject,
  repeaterSearch,
  repeaterTune,
  saveTextToDownloads,
} from '../api'
import {
  addMemoryDeduped,
  findEquivalent,
  memoriesStore,
  saveFavoriteFromDial,
  updateMemory,
  useMemories,
} from '../features/memories'
import {
  autoRadiusMi,
  BAND_CHIPS,
  bandOfMhz,
  deriveNames,
  favoriteName,
  isProgrammable,
  miToKm,
  modeBadge,
  NAME_CAPS,
  octant,
  RADIUS_CHIPS_MI,
  repeaterMemory,
  rigRepeaterParams,
  sanitizeName,
} from '../features/radioprog'
import { gridToLatLon, isValidGrid } from '../grid'
import { fmtDistanceKm, useUnits } from '../units'
import { Dialog } from './ui/Dialog'
import { pushToast } from '../toast'
import { parseChirpCsv, type Memory } from '../features/memories'

/** The single auto-saved working project in radioprog.json (named projects can
 * layer on later — the file format already holds many). */
const WORKING_PROJECT_ID = 'working'

/** localStorage for the last 5 successful query origins (chips). */
const RECENTS_KEY = 'nexus.program.recents.v1'
/** localStorage flag: the operator dismissed the CHIRP how-to dialog. */
const CHIRP_HOWTO_SEEN = 'nexus.program.chirpHowtoSeen.v1'

interface Recent {
  kind: 'grid' | 'city'
  label: string
  lat: number
  lon: number
}

function loadRecents(): Recent[] {
  try {
    const raw = JSON.parse(localStorage.getItem(RECENTS_KEY) ?? '[]')
    if (!Array.isArray(raw)) return []
    return raw
      .filter(
        (r): r is Recent =>
          r &&
          (r.kind === 'grid' || r.kind === 'city') &&
          typeof r.label === 'string' &&
          Number.isFinite(r.lat) &&
          Number.isFinite(r.lon),
      )
      .slice(0, 5)
  } catch {
    return []
  }
}

function pushRecent(r: Recent) {
  const list = [r, ...loadRecents().filter((x) => x.label !== r.label)].slice(0, 5)
  localStorage.setItem(RECENTS_KEY, JSON.stringify(list))
}

/** One builder row: the channel + whether the operator hand-edited its name
 * (edited names are never regenerated by the cap select). */
interface WorkRow {
  channel: ProgChannel
  nameEdited: boolean
}

interface Props {
  /** Station grid from Settings — the zero-input default origin. */
  myGrid: string
  /** CAT link alive — gates the per-row TUNE buttons. */
  catOk?: boolean
}

/**
 * Program — the radio-programming workbench: location → repeater directory →
 * pick → a curated channel list → CHIRP CSV / generic CSV (and, with CAT, tune
 * the rig to a machine right now). The CHANNEL LIST is the artifact; the
 * repeater results are a source feed that populates only on an explicit Fetch
 * (no auto-fetch, no polling, no map — this is a programming tool, not a
 * repeater directory).
 */
export function RadioProgView({ myGrid, catOk = false }: Props) {
  // ── query state ──
  const [originKind, setOriginKind] = useState<'station' | 'grid' | 'city'>('station')
  const [gridInput, setGridInput] = useState('')
  const [cityInput, setCityInput] = useState('')
  const [cityPick, setCityPick] = useState<GeoCandidate | null>(null)
  const [cityCands, setCityCands] = useState<GeoCandidate[]>([])
  const [geoBusy, setGeoBusy] = useState(false)
  const units = useUnits()
  const [radiusMi, setRadiusMi] = useState<number | 'auto'>('auto')
  const [bands, setBands] = useState<string[]>(['2m', '70cm'])
  const [showDigital, setShowDigital] = useState(false)
  const [onAirOnly, setOnAirOnly] = useState(true)
  const [search, setSearch] = useState('')
  const [recents, setRecents] = useState<Recent[]>(loadRecents)

  // ── results ──
  const [result, setResult] = useState<RepeaterSearchResult | null>(null)
  const [fetching, setFetching] = useState(false)
  const [fetchErr, setFetchErr] = useState('')

  // ── builder ──
  const [rows, setRows] = useState<WorkRow[]>([])
  const [nameCap, setNameCap] = useState(7)
  const [startAt, setStartAt] = useState(1)
  const [chirpDialog, setChirpDialog] = useState(false)
  const loaded = useRef(false)

  // Load the persisted working list once; save (debounced) on every change after.
  useEffect(() => {
    radioprogListProjects()
      .then((projects) => {
        const w = projects.find((p) => p.id === WORKING_PROJECT_ID)
        if (w) setRows(w.channels.map((channel) => ({ channel, nameEdited: true })))
        loaded.current = true
      })
      .catch(() => {
        loaded.current = true
      })
  }, [])
  const saveTimer = useRef<number | null>(null)
  useEffect(() => {
    if (!loaded.current) return
    if (saveTimer.current) window.clearTimeout(saveTimer.current)
    saveTimer.current = window.setTimeout(() => {
      const project: RadioProgProject = {
        id: WORKING_PROJECT_ID,
        name: 'My channels',
        createdUtc: 0,
        updatedUtc: 0,
        origin: { kind: originKind, grid: myGrid, label: originLabel(), lat: 0, lon: 0 },
        radiusKm: 0,
        channels: rows.map((r) => r.channel),
      }
      void radioprogSaveProject(project).catch(() => {})
    }, 800)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rows])

  const originLabel = useCallback((): string => {
    if (originKind === 'station') return myGrid.toUpperCase() || '—'
    if (originKind === 'grid') return gridInput.toUpperCase()
    return cityPick ? cityPick.displayName.split(',').slice(0, 2).join(',') : cityInput
  }, [originKind, myGrid, gridInput, cityPick, cityInput])

  /** Resolve the active origin to lat/lon (null = not resolvable yet). */
  const origin = useMemo((): { lat: number; lon: number } | null => {
    if (originKind === 'city') return cityPick ? { lat: cityPick.lat, lon: cityPick.lon } : null
    const g = (originKind === 'station' ? myGrid : gridInput).trim()
    if (!isValidGrid(g)) return null
    return gridToLatLon(g)
  }, [originKind, myGrid, gridInput, cityPick])

  const effRadiusMi = radiusMi === 'auto' ? autoRadiusMi(bands) : radiusMi

  const doFetch = useCallback(() => {
    if (!origin || fetching) return
    setFetching(true)
    setFetchErr('')
    repeaterSearch(origin.lat, origin.lon, miToKm(effRadiusMi))
      .then((res) => {
        setResult(res)
        const label = originLabel()
        if (label && label !== '—') {
          pushRecent({
            kind: originKind === 'city' ? 'city' : 'grid',
            label,
            lat: origin.lat,
            lon: origin.lon,
          })
          setRecents(loadRecents())
        }
      })
      .catch((e) => setFetchErr(String(e)))
      .finally(() => setFetching(false))
  }, [origin, fetching, effRadiusMi, originKind, originLabel])

  const searchCity = useCallback(() => {
    const q = cityInput.trim()
    if (!q || geoBusy) return
    setGeoBusy(true)
    setCityCands([])
    geocodeCity(q)
      .then((cands) => {
        setCityCands(cands)
        if (cands.length === 0) pushToast('No places matched — try "City, State"', 'info', 3000)
        if (cands.length === 1) setCityPick(cands[0])
      })
      .catch((e) => pushToast(String(e), 'error'))
      .finally(() => setGeoBusy(false))
  }, [cityInput, geoBusy])

  const useRecent = (r: Recent) => {
    // Recents carry resolved coordinates — re-fetch immediately from them.
    setOriginKind(r.kind === 'city' ? 'city' : 'grid')
    if (r.kind === 'grid') setGridInput(r.label)
    else {
      setCityInput(r.label)
      setCityPick({ displayName: r.label, lat: r.lat, lon: r.lon })
    }
  }

  // ── filtered picker rows ──
  const shown = useMemo(() => {
    if (!result) return []
    const q = search.trim().toUpperCase()
    return result.rows.filter((row) => {
      const r = row.record
      const band = bandOfMhz(r.outputMhz)
      if (bands.length > 0 && !bands.includes(band)) return false
      if (!showDigital && !r.fm) return false
      if (onAirOnly && !r.operational) return false
      if (q && !r.callsign.toUpperCase().includes(q) && !r.city.toUpperCase().includes(q))
        return false
      return true
    })
  }, [result, bands, showDigital, onAirOnly, search])

  const inList = useMemo(() => new Set(rows.map((r) => r.channel.id)), [rows])

  // Which shown machines are already starred — live from the shared bank, so the
  // stars stay right when the operator unstars one in the Memories section.
  const bank = useMemories()
  const starredIds = useMemo(() => {
    const out = new Set<string>()
    for (const row of shown) {
      const input = repeaterMemory(row.channel, '')
      const hit = findEquivalent(bank, {
        rxMhz: input.rxMhz,
        mode: input.mode,
        ctcssEncHz: input.ctcssEncHz,
      })
      if (hit?.favorite) out.add(row.channel.id)
    }
    return out
  }, [shown, bank])

  // ── builder ops ──
  /** A Memory (a CHIRP CSV row) as a Program channel — the reverse of `saveToBank`. Manual
   * and imported rows carry a `manual:` id so re-imports dedup. */
  const memoryToChannel = (m: Memory): ProgChannel => ({
    id: `manual:${m.rxMhz.toFixed(4)}:${m.name}`,
    name: m.name,
    rxMhz: m.rxMhz,
    duplex:
      m.offsetDir === 'split' ? 'split' : m.offsetDir === 'plus' ? 'plus' : m.offsetDir === 'minus' ? 'minus' : 'simplex',
    offsetMhz: m.offsetDir === 'split' ? (m.txMhz ?? m.rxMhz) - m.rxMhz : (m.offsetMhz ?? 0),
    toneMode: m.toneMode === 'tone' || m.toneMode === 'tsql' || m.toneMode === 'dtcs' ? m.toneMode : 'none',
    rtoneHz: m.ctcssEncHz ?? 0,
    ctoneHz: m.ctcssDecHz ?? m.ctcssEncHz ?? 0,
    dtcsCode: m.dtcsCode ?? 0,
    mode: m.mode.trim().toLowerCase() === 'nfm' ? 'nfm' : m.mode.trim().toLowerCase() === 'am' ? 'am' : 'fm',
    comment: m.notes ?? '',
    source: null,
  })

  /** Manual channel entry (operator ask, 2026-08-16): the directory is a FEED, and a repeater
   * it has wrong or missing must be enterable by hand — HearHam's coverage is thin in places
   * and the shared RepeaterBook path is still pending approval. */
  const addManual = () => {
    const freq = window.prompt('Frequency (MHz), e.g. 146.940')
    if (!freq) return
    const rxMhz = Number(freq)
    if (!Number.isFinite(rxMhz) || rxMhz <= 0) return
    const name = window.prompt('Name (blank = frequency)') ?? ''
    const off = window.prompt('Offset: + / - / blank for simplex') ?? ''
    const tone = window.prompt('CTCSS tone Hz (blank = none)') ?? ''
    const toneHz = Number(tone)
    const ch: ProgChannel = {
      id: `manual:${rxMhz.toFixed(4)}:${name || 'manual'}`,
      name: name || `${rxMhz.toFixed(3)} FM`,
      rxMhz,
      duplex: off.trim() === '+' ? 'plus' : off.trim() === '-' ? 'minus' : 'simplex',
      offsetMhz: 0,
      toneMode: Number.isFinite(toneHz) && toneHz > 0 ? 'tone' : 'none',
      rtoneHz: Number.isFinite(toneHz) && toneHz > 0 ? toneHz : 0,
      ctoneHz: 0,
      dtcsCode: 0,
      mode: 'fm',
      comment: '',
      source: null,
    }
    setRows((rs) =>
      rs.some((r) => r.channel.id === ch.id) ? rs : [...rs, { channel: ch, nameEdited: name !== '' }],
    )
  }

  const importInputRef = useRef<HTMLInputElement>(null)
  const importCsv = async (file: File) => {
    const text = await file.text()
    const mems = parseChirpCsv(text)
    if (mems.length === 0) {
      pushToast('Not a CHIRP CSV — need a header row with Frequency and Mode', 'error')
      return
    }
    setRows((rs) => {
      const have = new Set(rs.map((r) => r.channel.id))
      const add = mems.map(memoryToChannel).filter((c) => !have.has(c.id))
      return [...rs, ...add.map((channel) => ({ channel, nameEdited: true }))]
    })
    pushToast(`Imported ${mems.length} channels from CHIRP CSV`, 'success')
  }

  const addRow = (row: RepeaterSearchRow) => {
    if (inList.has(row.channel.id)) {
      setRows((rs) => rs.filter((r) => r.channel.id !== row.channel.id))
      return
    }
    setRows((rs) => [...rs, { channel: { ...row.channel }, nameEdited: false }])
  }
  const addAllShown = async () => {
    const candidates = shown.filter(
      (row) => isProgrammable(row.record) && !inList.has(row.channel.id),
    )
    if (candidates.length === 0) return
    if (
      candidates.length > 50 &&
      !(await confirmDialog({
        title: `Add ${candidates.length} channels?`,
        confirmLabel: 'Add channels',
      }))
    )
      return
    setRows((rs) => [
      ...rs,
      ...candidates.slice(0, 200).map((row) => ({ channel: { ...row.channel }, nameEdited: false })),
    ])
  }
  const move = (i: number, d: -1 | 1) => {
    setRows((rs) => {
      const j = i + d
      if (j < 0 || j >= rs.length) return rs
      const next = rs.slice()
      ;[next[i], next[j]] = [next[j], next[i]]
      return next
    })
  }
  const remove = (i: number) => setRows((rs) => rs.filter((_, k) => k !== i))
  const rename = (i: number, name: string) =>
    setRows((rs) =>
      rs.map((r, k) => (k === i ? { ...r, channel: { ...r.channel, name }, nameEdited: true } : r)),
    )

  // Auto-derived names for rows the operator hasn't touched (cap-aware).
  const displayRows = useMemo(() => {
    const auto = deriveNames(
      rows.map((r) => ({
        callsign: r.channel.source?.callsign ?? r.channel.name,
        city: r.channel.comment,
        outputMhz: r.channel.rxMhz,
      })),
      nameCap,
    )
    return rows.map((r, i) => ({
      ...r,
      displayName: r.nameEdited ? r.channel.name : auto[i],
    }))
  }, [rows, nameCap])

  const dupNames = useMemo(() => {
    const seen = new Map<string, number>()
    for (const r of displayRows) {
      const n = sanitizeName(r.displayName, nameCap)
      seen.set(n, (seen.get(n) ?? 0) + 1)
    }
    return new Set([...seen.entries()].filter(([, c]) => c > 1).map(([n]) => n))
  }, [displayRows, nameCap])

  const attribution = result?.source === 'repeaterbook'
    ? 'Data courtesy of RepeaterBook.com'
    : 'Repeater data from hearham.com'

  const exportList = (format: 'chirp' | 'csv') => {
    const channels = displayRows.map((r) => ({ ...r.channel, name: r.displayName }))
    const analog = channels.filter((c) => c.mode === 'fm' || c.mode === 'nfm' || c.mode === 'am')
    if (format === 'chirp' && analog.length === 0) {
      pushToast('No FM channels in the list — digital channels export in a later version', 'info')
      return
    }
    void exportChannels(channels, format, nameCap, attribution)
      .then((text) => {
        const stamp = new Date().toISOString().slice(0, 10)
        const name = format === 'chirp' ? `nexus-chirp-${stamp}.csv` : `nexus-channels-${stamp}.csv`
        return saveTextToDownloads(name, text).then((path) => {
          pushToast(
            format === 'chirp'
              ? `Saved ${path} — open CHIRP ▸ File ▸ Import, then upload to your radio`
              : `Saved ${path}`,
            'success',
            6000,
          )
        })
      })
      .catch((e) => pushToast(String(e), 'error'))
  }

  const onExportChirp = () => {
    if (localStorage.getItem(CHIRP_HOWTO_SEEN) === '1') exportList('chirp')
    else setChirpDialog(true)
  }

  /** Tune the CAT rig to a repeater NOW — one atomic backend step that routes on
   * FM (so 2 m repeater work reaches the FM radio even when the operator came
   * from a digital section) and lands the shift/offset/tone with the QSY. */
  const tuneTo = (c: ProgChannel) => {
    const { shift, offsetHz, toneHz } = rigRepeaterParams(c)
    void repeaterTune(c.rxMhz, shift, offsetHz, toneHz)
      .then(() => {
        const shiftLabel =
          shift === 'simplex'
            ? 'simplex'
            : `${shift === 'plus' ? '+' : '−'}${(offsetHz / 1e6).toFixed(2)} MHz`
        pushToast(
          `Tuned ${c.rxMhz.toFixed(4)} FM — ${shiftLabel}${toneHz ? ` · tone ${toneHz.toFixed(1)}` : ''}`,
          'success',
          4000,
        )
      })
      .catch((e) => pushToast(String(e), 'error'))
  }

  /** ★ one machine straight into the favorites list — the whole point of the
   * feature: fetch, star, and it's on the cockpit MEM strip and in Memories
   * without a trip through the channel-list builder. Starring an equivalent
   * channel the bank already holds stars THAT row rather than duplicating it
   * (memoryKey identity), and the star toggles back off. */
  const toggleStar = (row: RepeaterSearchRow) => {
    const input = repeaterMemory(row.channel, favoriteName(row.channel), {
      lat: row.record.lat,
      lon: row.record.lon,
    })
    let msg = ''
    memoriesStore.update((bank) => {
      const existing = findEquivalent(bank, {
        rxMhz: input.rxMhz,
        mode: input.mode,
        ctcssEncHz: input.ctcssEncHz,
      })
      if (existing?.favorite) {
        msg = `${existing.name} unstarred — still in Memories`
        return updateMemory(bank, existing.id, { favorite: false })
      }
      const res = saveFavoriteFromDial(bank, input)
      msg =
        res.result === 'starred'
          ? `${existing?.name ?? input.name} starred — already in Memories`
          : `${input.name} ★ — on the cockpit MEM strip and in Memories`
      return res.bank
    })
    pushToast(msg, 'success', 4000)
  }

  /** Save the whole list into the shared Memories store (with the FM repeater
   * fields, so recall keys the machine — not just the output). Deduped on
   * freq+mode+tone so re-saving the same list never piles duplicates; the
   * SHARED store means the Memories section + cockpit MEM strips update live
   * (the old direct-to-storage write went stale until reload). */
  const saveToBank = () => {
    let n = 0
    let dup = 0
    memoriesStore.update((bank) => {
      let next = bank
      for (const r of displayRows) {
        const c = r.channel
        if (!(c.mode === 'fm' || c.mode === 'nfm' || c.mode === 'am')) continue
        // No site coordinates here: the builder list persists channels only
        // (radioprog.json), so a reloaded row has no record to read lat/lon from.
        // ★-ing from the results list is the path that carries them.
        const res = addMemoryDeduped(
          next,
          repeaterMemory(c, sanitizeName(r.displayName, nameCap) || c.name),
        )
        next = res.bank
        if (res.added) n += 1
        else dup += 1
      }
      return next
    })
    pushToast(
      n
        ? `${n} channel${n === 1 ? '' : 's'} saved to Memories${dup ? ` (${dup} already there)` : ''} — star ★ the ones you want on the cockpit MEM strip`
        : dup
          ? 'All of these are already in Memories'
          : 'No FM channels to save',
      n ? 'success' : 'info',
      5000,
    )
  }

  const fmtAge = (unix: number): string => {
    const mins = Math.max(0, Math.round((Date.now() / 1000 - unix) / 60))
    if (mins < 60) return `${mins}m ago`
    if (mins < 60 * 48) return `${Math.round(mins / 60)}h ago`
    return `${Math.round(mins / 1440)}d ago`
  }

  const offsetLabel = (c: ProgChannel): string => {
    if (c.duplex === 'simplex') return '—'
    if (c.duplex === 'split') return `→${c.offsetMhz.toFixed(3)}`
    return `${c.duplex === 'plus' ? '+' : '-'}${c.offsetMhz.toFixed(1)}`
  }
  const toneLabel = (c: ProgChannel): string => {
    if (c.toneMode === 'none') return '—'
    if (c.toneMode === 'dtcs') return `D${String(c.dtcsCode).padStart(3, '0')}`
    return c.rtoneHz.toFixed(1)
  }

  return (
    <section className="radioprog panel">
      <div className="panel-header">
        <h2>Program</h2>
        <span className="awards-sub">
          Build channel lists for your radios — repeaters near a location, exported for CHIRP or
          tuned on your rig
        </span>
      </div>

      <div className="rp-body">
        {/* ── SOURCE pane: the query tool ── */}
        <div className="rp-source">
          <div className="rp-origin" role="group" aria-label="Search origin">
            <span className="rp-lbl">Near</span>
            <button
              type="button"
              className={`filter-chip${originKind === 'station' ? ' active' : ''}`}
              onClick={() => setOriginKind('station')}
              title="Your station grid from Settings"
            >
              My station {myGrid ? `· ${myGrid.toUpperCase()}` : ''}
            </button>
            <button
              type="button"
              className={`filter-chip${originKind === 'grid' ? ' active' : ''}`}
              onClick={() => setOriginKind('grid')}
            >
              Grid
            </button>
            <button
              type="button"
              className={`filter-chip${originKind === 'city' ? ' active' : ''}`}
              onClick={() => setOriginKind('city')}
            >
              City
            </button>
            {originKind === 'grid' && (
              <input
                type="text"
                className={`settings-input mono rp-grid${gridInput && !isValidGrid(gridInput.trim()) ? ' invalid' : ''}`}
                value={gridInput}
                maxLength={6}
                placeholder="FN31"
                aria-label="Grid square"
                onChange={(e) => setGridInput(e.target.value.toUpperCase())}
              />
            )}
            {originKind === 'city' && (
              <span className="rp-city">
                <input
                  type="text"
                  className="settings-input rp-city-input"
                  value={cityInput}
                  placeholder="Gatlinburg, TN"
                  aria-label="City"
                  onChange={(e) => {
                    setCityInput(e.target.value)
                    setCityPick(null)
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') searchCity()
                  }}
                />
                <button
                  type="button"
                  className="filter-chip"
                  onClick={searchCity}
                  disabled={geoBusy || !cityInput.trim()}
                >
                  {geoBusy ? 'Searching…' : 'Search'}
                </button>
              </span>
            )}
          </div>
          {originKind === 'city' && cityCands.length > 1 && !cityPick && (
            <div className="rp-city-cands" role="listbox" aria-label="Matching places">
              {cityCands.map((c) => (
                <button
                  key={c.displayName}
                  type="button"
                  className="filter-chip"
                  onClick={() => setCityPick(c)}
                >
                  {c.displayName}
                </button>
              ))}
            </div>
          )}
          {recents.length > 0 && (
            <div className="rp-recents" role="group" aria-label="Recent searches">
              <span className="rp-lbl">Recent</span>
              {recents.map((r) => (
                <button
                  key={r.label}
                  type="button"
                  className="filter-chip rp-recent"
                  onClick={() => useRecent(r)}
                  title="Reuse this search origin"
                >
                  {r.label}
                </button>
              ))}
            </div>
          )}

          <div className="rp-radius" role="group" aria-label="Search radius">
            <span className="rp-lbl">Radius</span>
            {RADIUS_CHIPS_MI.map((mi) => (
              <button
                key={mi}
                type="button"
                className={`filter-chip${radiusMi === mi ? ' active' : ''}`}
                onClick={() => setRadiusMi(mi)}
              >
                {fmtDistanceKm(mi * 1.609344, units)}
              </button>
            ))}
            <button
              type="button"
              className={`filter-chip${radiusMi === 'auto' ? ' active' : ''}`}
              onClick={() => setRadiusMi('auto')}
              title="Radius from the selected bands' realistic repeater reach"
            >
              Auto
            </button>
            {radiusMi === 'auto' && (
              <span className="rp-hint">
                = {fmtDistanceKm(effRadiusMi * 1.609344, units)} ({bands.length ? bands.join('+') : 'all bands'})
              </span>
            )}
          </div>

          <div className="rp-fetch-row">
            <button
              type="button"
              className="filter-chip pota-refresh-btn rp-fetch"
              onClick={doFetch}
              disabled={!origin || fetching}
              title={
                origin
                  ? `Fetch repeaters within ${fmtDistanceKm(effRadiusMi * 1.609344, units)}`
                  : 'Pick a valid origin first (grid or city)'
              }
            >
              {fetching ? '⟳ Fetching…' : '⟳ Fetch repeaters'}
            </button>
            {result && (
              <span className="rp-stamp" title="Directory data age (cached per source, weekly)">
                {result.source === 'repeaterbook' ? 'RepeaterBook' : 'hearham'} ·{' '}
                {fmtAge(result.fetchedUtc)}
                {result.stale ? ' · stale (fetch failed, cached data shown)' : ''}
              </span>
            )}
          </div>
          {fetchErr && (
            <div className="rp-error" role="alert">
              {fetchErr}{' '}
              <button type="button" className="filter-chip" onClick={doFetch}>
                Retry
              </button>
            </div>
          )}
          {result?.coverageGap && (
            <div className="rp-note" role="status">
              hearham lists no <strong>{result.coverageGap}</strong> repeaters here, which is
              unusual for an area that has any — its rural coverage is patchy, so this list is
              probably missing machines. Adding a RepeaterBook API token in{' '}
              <strong>Settings ▸ Integrations</strong> fills the gap.
            </div>
          )}

          <div className="rp-filters" role="group" aria-label="Result filters">
            <button
              type="button"
              className={`filter-chip${bands.length === 0 ? ' active' : ''}`}
              onClick={() => setBands([])}
            >
              All
            </button>
            {BAND_CHIPS.map((b) => (
              <button
                key={b}
                type="button"
                className={`filter-chip${bands.includes(b) ? ' active' : ''}`}
                onClick={() =>
                  setBands((bs) => (bs.includes(b) ? bs.filter((x) => x !== b) : [...bs, b]))
                }
              >
                {b}
              </button>
            ))}
            <span className="rp-filter-gap" />
            <button
              type="button"
              className={`filter-chip${!showDigital ? ' active' : ''}`}
              onClick={() => setShowDigital(false)}
              title="FM repeaters only — what v1 programs"
            >
              FM
            </button>
            <button
              type="button"
              className={`filter-chip${showDigital ? ' active' : ''}`}
              onClick={() => setShowDigital(true)}
              title="Also list DMR / D-STAR / Fusion machines (badged; programming them comes later)"
            >
              +Digital
            </button>
            <button
              type="button"
              className={`filter-chip${onAirOnly ? ' active' : ''}`}
              onClick={() => setOnAirOnly((v) => !v)}
              title="Hide machines the directory marks off-air"
            >
              On-air only
            </button>
            <input
              type="search"
              className="settings-input rp-search"
              value={search}
              placeholder="Filter call / city…"
              aria-label="Filter results"
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          {result && (
            <div className="rp-count">
              {shown.length} of {result.rows.length} shown · nearest first
              {shown.some((r) => isProgrammable(r.record) && !inList.has(r.channel.id)) && (
                <button type="button" className="filter-chip" onClick={addAllShown}>
                  ＋ Add all shown
                </button>
              )}
            </div>
          )}

          <div className="rp-results" role="table" aria-label="Repeaters">
            {!result && !fetching && (
              <p className="aw-empty">
                Pick a location and press <strong>Fetch repeaters</strong> — results land here;
                ADD the machines you want on your radio.
              </p>
            )}
            {result && shown.length === 0 && (
              <p className="aw-empty">
                No {showDigital ? '' : 'FM '}repeaters within {fmtDistanceKm(effRadiusMi * 1.609344, units)}.
                {radiusMi !== 200 && (
                  <button
                    type="button"
                    className="filter-chip"
                    onClick={() => setRadiusMi(radiusMi === 'auto' ? 100 : 200)}
                  >
                    Try {fmtDistanceKm((radiusMi === 'auto' ? 100 : 200) * 1.609344, units)}
                  </button>
                )}
                {!showDigital && (
                  <button type="button" className="filter-chip" onClick={() => setShowDigital(true)}>
                    Show digital
                  </button>
                )}
              </p>
            )}
            {shown.map((row) => {
              const r = row.record
              const c = row.channel
              const added = inList.has(c.id)
              const programmable = isProgrammable(r)
              const badge = modeBadge(r)
              return (
                <div
                  key={c.id}
                  role="row"
                  className={`rp-row${!r.operational ? ' offair' : ''}${!programmable ? ' digital' : ''}`}
                >
                  <span className="rp-call mono" role="cell">
                    {r.callsign || '—'}
                  </span>
                  <span className="rp-freq mono" role="cell">
                    {r.outputMhz.toFixed(4).replace(/0+$/, '').replace(/\.$/, '.0')}
                  </span>
                  <span className="rp-off mono" role="cell">
                    {offsetLabel(c)}
                  </span>
                  <span className="rp-tone mono" role="cell">
                    {toneLabel(c)}
                  </span>
                  <span className="rp-dist mono" role="cell" title={`${r.city}${r.state ? `, ${r.state}` : ''}`}>
                    {fmtDistanceKm(r.distanceKm, units)} {octant(r.bearingDeg)}
                  </span>
                  <span className="rp-badges" role="cell">
                    {badge && <span className="pota-badge rp-mode-badge">{badge}</span>}
                    {!r.operational && <span className="pota-badge rp-offair-badge">OFF-AIR</span>}
                  </span>
                  <span className="rp-actions" role="cell">
                    {programmable && (
                      <button
                        type="button"
                        className={`rp-star${starredIds.has(c.id) ? ' on' : ''}`}
                        onClick={() => toggleStar(row)}
                        aria-pressed={starredIds.has(c.id)}
                        title={
                          starredIds.has(c.id)
                            ? 'Unstar — keeps the channel in Memories, drops it off the cockpit strip'
                            : 'Star this repeater — saves it to Memories and the cockpit MEM strip for one-click tuning'
                        }
                      >
                        {starredIds.has(c.id) ? '★' : '☆'}
                      </button>
                    )}
                    {catOk && programmable && (
                      <button
                        type="button"
                        className="pota-hunt-btn rp-tune"
                        onClick={() => tuneTo(c)}
                        title="Tune your CAT rig to this repeater now (FM + shift + offset + tone)"
                      >
                        Tune
                      </button>
                    )}
                    <button
                      type="button"
                      className={`pota-hunt-btn rp-add${added ? ' added' : ''}`}
                      disabled={!programmable && !added}
                      onClick={() => addRow(row)}
                      title={
                        programmable
                          ? added
                            ? 'Remove from the channel list'
                            : 'Add to the channel list'
                          : 'Digital repeater — programming DMR/D-STAR/Fusion comes in a later version'
                      }
                    >
                      {added ? '✓ Added' : '＋ Add'}
                    </button>
                  </span>
                </div>
              )
            })}
          </div>

          <div className="settings-hint rp-attribution">
            {result?.source === 'hearham' || !result ? (
              <a href="https://hearham.com" target="_blank" rel="noreferrer">
                Repeater data from hearham.com
              </a>
            ) : (
              <a href="https://www.repeaterbook.com" target="_blank" rel="noreferrer">
                Data courtesy of RepeaterBook.com
              </a>
            )}
            {originKind === 'city' && (
              <span> · Geocoding © OpenStreetMap contributors</span>
            )}
          </div>
        </div>

        {/* ── CHANNEL LIST pane: the artifact ── */}
        <aside className="rp-builder">
          <div className="rp-builder-head">
            <span className="rp-builder-title">
              Channel list <span className="np-count">{rows.length}</span>
            </span>
            <label className="rp-cap">
              Max name
              <select
                className="settings-input"
                value={nameCap}
                onChange={(e) => setNameCap(Number(e.target.value))}
                title="Your radio's channel-name length — auto names re-derive to fit (hand-edited names are kept)"
              >
                {NAME_CAPS.map((c) => (
                  <option key={c.cap} value={c.cap}>
                    {c.label}
                  </option>
                ))}
              </select>
            </label>
            <label className="rp-startat" title="First memory slot number (keep your existing channels)">
              Start at
              <input
                type="number"
                className="settings-input"
                min={1}
                max={999}
                value={startAt}
                onChange={(e) => setStartAt(Math.max(1, Math.round(Number(e.target.value) || 1)))}
              />
            </label>
          </div>

          <div className="rp-chan-rows">
            {displayRows.length === 0 && (
              <p className="aw-empty">
                No channels yet — fetch repeaters on the left and ADD the ones you want on your
                radio.
              </p>
            )}
            {displayRows.map((r, i) => {
              const clean = sanitizeName(r.displayName, nameCap)
              const dup = dupNames.has(clean)
              const over = r.displayName.trim().length > nameCap
              return (
                <div key={r.channel.id} className={`rp-chan-row${dup ? ' dup' : ''}`}>
                  <span className="rp-chan-num mono">{startAt + i}</span>
                  <input
                    type="text"
                    className={`settings-input mono rp-chan-name${dup || over ? ' invalid' : ''}`}
                    value={r.displayName}
                    maxLength={24}
                    aria-label={`Channel ${startAt + i} name`}
                    onChange={(e) => rename(i, e.target.value)}
                    title={
                      dup
                        ? 'Duplicate name — the radio will show two identical channels'
                        : over
                          ? `Longer than ${nameCap} — exports as "${clean}"`
                          : undefined
                    }
                  />
                  <span className="rp-chan-freq mono">{r.channel.rxMhz.toFixed(4)}</span>
                  <span className="rp-chan-off mono">{offsetLabel(r.channel)}</span>
                  <span className="rp-chan-tone mono">{toneLabel(r.channel)}</span>
                  <span className="rp-chan-btns">
                    <button type="button" onClick={() => move(i, -1)} disabled={i === 0} aria-label="Move up">
                      ▲
                    </button>
                    <button
                      type="button"
                      onClick={() => move(i, 1)}
                      disabled={i === displayRows.length - 1}
                      aria-label="Move down"
                    >
                      ▼
                    </button>
                    <button type="button" onClick={() => remove(i)} aria-label="Remove">
                      ✕
                    </button>
                  </span>
                </div>
              )
            })}
          </div>

          <div className="rp-deliver">
            <button
              type="button"
              className="settings-refresh"
              onClick={addManual}
              title="Type in a repeater or simplex channel the directory doesn't have (or has wrong)"
            >
              Add by hand…
            </button>
            <button
              type="button"
              className="settings-refresh"
              onClick={() => importInputRef.current?.click()}
              title="Import a CHIRP CSV — the same format Export for CHIRP writes, and what CHIRP itself saves"
            >
              Import CHIRP CSV…
            </button>
            <input
              ref={importInputRef}
              type="file"
              accept=".csv,text/csv"
              hidden
              onChange={(e) => {
                const f = e.target.files?.[0]
                if (f) void importCsv(f)
                e.target.value = ''
              }}
            />
            <button
              type="button"
              className="settings-save rp-export-chirp"
              disabled={rows.length === 0}
              onClick={onExportChirp}
              title="Save a CHIRP-ready CSV — CHIRP (free) flashes nearly every radio from it"
            >
              Export for CHIRP…
            </button>
            <button
              type="button"
              className="settings-refresh"
              disabled={rows.length === 0}
              onClick={() => exportList('csv')}
              title="Plain CSV — spreadsheets, Anytone CPS, RT Systems"
            >
              Export CSV
            </button>
            <button
              type="button"
              className="settings-refresh"
              disabled={rows.length === 0}
              onClick={saveToBank}
              title="Save these channels into Nexus's own memory bank (the Phone cockpit's MEMORY recall list) — recall retunes the rig with shift + tone"
            >
              Save to Memory Bank
            </button>
            <button
              type="button"
              className="settings-refresh rp-clear"
              disabled={rows.length === 0}
              onClick={() => {
                void (async () => {
                  if (
                    await confirmDialog({
                      title: 'Clear the whole channel list?',
                      confirmLabel: 'Clear list',
                      danger: true,
                    })
                  )
                    setRows([])
                })()
              }}
            >
              Clear
            </button>
          </div>
        </aside>
      </div>

      <Dialog
        open={chirpDialog}
        onOpenChange={setChirpDialog}
        title="Flash with CHIRP"
        description="Nexus builds the list; CHIRP drives the cable. One list, every radio you own."
      >
        <ol className="rp-chirp-steps">
          <li>Nexus saves a CHIRP-ready CSV to your Downloads.</li>
          <li>
            Open CHIRP (free, ~1,000 radios) → <strong>File ▸ Import</strong> and pick the file.
          </li>
          <li>Connect your programming cable → <strong>Radio ▸ Upload To Radio</strong>.</li>
        </ol>
        <p className="settings-hint">
          <a href="https://chirpmyradio.com" target="_blank" rel="noreferrer">
            Get CHIRP ↗
          </a>
        </p>
        <div className="rp-chirp-actions">
          <label className="settings-hint rp-chirp-skip">
            <input
              type="checkbox"
              onChange={(e) => {
                if (e.target.checked) localStorage.setItem(CHIRP_HOWTO_SEEN, '1')
                else localStorage.removeItem(CHIRP_HOWTO_SEEN)
              }}
            />
            Don't show this again — just save the file
          </label>
          <button
            type="button"
            className="settings-save"
            onClick={() => {
              setChirpDialog(false)
              exportList('chirp')
            }}
          >
            Save the CSV
          </button>
        </div>
      </Dialog>
    </section>
  )
}
